### ISSUE TITLE
Slowness & Dates are not updating

### ISSUE THREAD

**Issue by sulaganathan** [moodleou/moodle-report_editdates#21]
1. When the course is accessed, and the Dates Report (Admin >Reports>Dates) is accessed, there is a very slow response in this course. It takes minutes to build the list of objects and then when the filter is changed, the response time is equally slow.

1. I've tested this with the moodle course. with the following results:

- Using the Dates Report, I changed date for all Assignment activities in the course. I saved the changes. None of the dates were updated on the activities in the course.

- I re-entered the Dates Report, and had a slow response to accessing the pull down menu to select and activity type (about 15 seconds) and Expand all (about 15 seconds as well). I did NOT have this slow response with the first access during this trial.

- I changed the date for one activity (Internet Introduction Q&A Forum Grade) and saved the change. The updated date was recorded on the activity.

-  Using the Dates Report, I changed the date for two activities  (Internet Introduction Q&A Forum Grade  and PowerPoint Reflection) and saved the changes. The updated date was recorded on the activities.

- Using the Dates Report, I changed the dates for all assignment activities in the course (same process I followed in step 2.1 above) and all of the dates were updated to the revised dates.

Can you identify why the dates are not being updated as expected? In the current process, the updates are unreliable and faculty are wasting time updating activities with the Dates Report since the revised dates are not sticking to the actual activities.

please refer the attached screenshot for references
![dates2](https://user-images.githubusercontent.com/11982111/52810811-774b0900-30b9-11e9-8731-ba5f0da700f9.JPG)
![dates3](https://user-images.githubusercontent.com/11982111/52810813-77e39f80-30b9-11e9-8761-074a47e68268.JPG)

**Comment by sulaganathan** [comment]
@timhunt  I would appreciate if you could review and provide your thoughts on this

**Comment by timhunt** [comment]
I saw this last week, and read it, but it did not make any sense.

The alleged performance measurements are just weird. MoodleForm->setDefaults does not do very much work normally, so it makes no sense that function would take 5 seconds to execute. Obviously, the full story is not shown in your screen-grabs.

Also, if expending a drop-down menu in your web browser is taking 15 seconds, well that does not involve any Moodle code at all. that is just HTML in your web browser. The only reason I can see why that would be so slow is if you are running Internet explorer.

I don't know why dates would not save. I mean, presumably it is a bug, but I have been too busy to try to reproduce it, and giving how badly the report is working on your system in general, it might just be your system being unreliable rather than a code bug.

**Comment by sulaganathan** [comment]
Hi @timhunt .

Thank you for your prompt response.

Few clarifications on it,

- The slowness is not because of IE, it happens in the latest version of Chrome, FF
- Re: 15 secs, we are getting the browser got hanged for a moment
- We have many clients have been using this Moodle environment and no performance issue, even in larger reports

I am happy to provide more details on this, please let me know

**Comment by sulaganathan** [comment]
@timhunt  I would appreciate if you could review this and let us know

**Comment by timhunt** [comment]
I don't have anything to add to my last response.
